namespace :rails_nexus do
  namespace :tailwind do
    desc "Generate Tailwind v4 @source entries for RailsNexus views/helpers (OUT=app/assets/stylesheets/_rails_nexus_sources.css ENTRY=app/assets/stylesheets/application.tailwind.css)"
    task sources: :environment do
      root = RailsNexus::Engine.root
      out = ENV["OUT"] || "app/assets/stylesheets/_rails_nexus_sources.css"

      content = <<~CSS
        /* Generated by bin/rails rails_nexus:tailwind:sources - do not edit. Re-run after gem updates or on new machines/containers. */
        @source "#{root}/app/views/**/*.erb";
        @source "#{root}/app/helpers/**/*.rb";
      CSS

      FileUtils.mkdir_p(File.dirname(out))
      File.write(out, content)
      puts "Wrote #{out}"

      entry = ENV["ENTRY"]
      entry ||= "app/assets/stylesheets/application.tailwind.css" if File.exist?("app/assets/stylesheets/application.tailwind.css")

      if entry && File.file?(entry)
        import_line = "@import \"./#{File.basename(out)}\";"
        body = File.read(entry)

        if body.include?(File.basename(out))
          puts "#{entry} already imports #{File.basename(out)}"
        else
          File.write(entry, body.sub(/\A/, "#{import_line}\n"))
          puts "Added #{import_line} to #{entry}"
        end
      elsif !entry
        puts "Add this to your Tailwind entry stylesheet:"
        puts "  @import \"./#{File.basename(out)}\";"
      end
    end
  end
end
