#!/bin/bash
# RailsNexus Backup Helper Script
# Generated by: rails generate rails_nexus:backup
#
# Usage:
#   ./backup_helper.sh run <model>     Run a backup model
#   ./backup_helper.sh list            List backup files
#   ./backup_helper.sh status          Show backup health status
#   ./backup_helper.sh clean <days>    Remove backups older than N days

set -e

# Configuration
BACKUP_DIR="${BACKUP_DUMP_PATH:-storage/rails_nexus/backups}"
BUNDLE_PATH="${BUNDLE_PATH:-.bundle}"
RUBY_ENV="${RUBY_ENV:-production}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Run a backup
run_backup() {
  local model="$1"
  if [ -z "$model" ]; then
    log_error "Usage: $0 run <model_name>"
    exit 1
  fi
  
  # Lock to prevent concurrent runs
  LOCKFILE="/tmp/rails_nexus_backup_${model}.lock"
  exec 200>"$LOCKFILE"
  if ! flock -n 200; then
    log_warn "Backup '$model' is already running. Skipping."
    exit 0
  fi
  
  log_info "Running backup: $model"
  cd "$(dirname "$0")/../../.."
  
  if bundle exec backup perform -t "$model" --triggered_by rails_nexus; then
    log_info "Backup '$model' completed successfully."
  else
    log_error "Backup '$model' FAILED."
    exit 1
  fi
}

# List backup files
list_backups() {
  local dir="$BACKUP_DIR"
  if [ ! -d "$dir" ]; then
    log_warn "No backup directory found at: $dir"
    exit 0
  fi
  
  echo "Backup files in: $dir"
  echo "─────────────────────────────────────────────"
  printf "%-40s %10s %s\n" "FILE" "SIZE" "MODIFIED"
  echo "─────────────────────────────────────────────"
  
  find "$dir" -maxdepth 1 -type f -name "*.tar.gz*" -o -name "*.sql.gz*" | sort -r | head -20 | while read -r f; do
    size=$(du -h "$f" | cut -f1)
    modified=$(stat -c "%y" "$f" 2>/dev/null | cut -d'.' -f1 || date -r "$f" "+%Y-%m-%d %H:%M")
    printf "%-40s %10s %s\n" "$(basename "$f")" "$size" "$modified"
  done
}

# Show backup status
show_status() {
  local dir="$BACKUP_DIR"
  if [ ! -d "$dir" ]; then
    echo "Status: NOT_CONFIGURED"
    echo "No backup directory at: $dir"
    exit 0
  fi
  
  local total_files
  total_files=$(find "$dir" -maxdepth 1 -type f | wc -l)
  local total_size
  total_size=$(du -sh "$dir" 2>/dev/null | cut -f1 || echo "0B")
  
  local latest_file
  latest_file=$(find "$dir" -maxdepth 1 -type f -name "*.tar.gz*" -o -name "*.sql.gz*" 2>/dev/null | sort -r | head -1)
  
  if [ -z "$latest_file" ]; then
    echo "Status: WARNING - No backup files found"
  else
    local age_hours
    age_hours=$(( ($(date +%s) - $(stat -c "%Y" "$latest_file" 2>/dev/null || stat -f "%m" "$latest_file")) / 3600 ))
    
    if [ "$age_hours" -lt 24 ]; then
      echo "Status: HEALTHY"
    elif [ "$age_hours" -lt 72 ]; then
      echo "Status: WARNING - Last backup ${age_hours}h ago"
    else
      echo "Status: CRITICAL - Last backup ${age_hours}h ago"
    fi
  fi
  
  echo "Files: $total_files"
  echo "Size: $total_size"
  [ -n "$latest_file" ] && echo "Latest: $(basename "$latest_file")"
}

# Clean old backups
clean_backups() {
  local days="${1:-30}"
  local dir="$BACKUP_DIR"
  
  if [ ! -d "$dir" ]; then
    log_warn "No backup directory found at: $dir"
    exit 0
  fi
  
  log_info "Removing backups older than $days days..."
  find "$dir" -maxdepth 1 -type f -mtime +"$days" -delete
  log_info "Cleanup complete."
}

# Main
case "${1:-help}" in
  run)
    run_backup "$2"
    ;;
  list)
    list_backups
    ;;
  status)
    show_status
    ;;
  clean)
    clean_backups "$2"
    ;;
  *)
    echo "RailsNexus Backup Helper"
    echo ""
    echo "Usage: $0 <command> [args]"
    echo ""
    echo "Commands:"
    echo "  run <model>    Run a backup model (e.g., daily_backup)"
    echo "  list           List recent backup files"
    echo "  status         Show backup health status"
    echo "  clean [days]   Remove backups older than N days (default: 30)"
    ;;
esac
