# encoding: utf-8

##
# Backup v5.x Configuration
# Generated by rails_nexus
#
# Documentation: http://backup.github.io/backup
#

# Logging
# Logger.configure do
#   console.quiet     = true
#   logfile.max_bytes = 2_000_000
#   syslog.enabled    = true
#   syslog.ident      = '<%= Rails.application.class.module_parent_name.underscore %>_backup'
# end

# Storage defaults
# Storage::Local.defaults do |local|
#   local.path = 'storage/rails_nexus/backups'
# end

# Notifier defaults
# Notifier::Mail.defaults do |mail|
#   mail.from = 'backup@<%= Rails.application.class.module_parent_name.underscore %>.com'
#   mail.to   = 'admin@<%= Rails.application.class.module_parent_name.underscore %>.com'
# end
