# frozen_string_literal: true
# RailsNexus Backup Schedule
# Generated by: rails generate rails_nexus:backup
#
# This file is parsed by the BackupService to show schedule info in the UI.
# Actual cron should be installed separately: whenever --write-crontab

# ─── Backup Schedule ──────────────────────────────────────────────

# Full backup daily at 2:00 AM (all tables, local only)
every 1.day, at: "2:00 am" do
  command "cd #{File.expand_path('../..', __FILE__)} && bundle exec backup perform -t full_backup --triggered_by system"
end

# Incremental backup every 4 hours (skipping large tables)
every 4.hours do
  command "cd #{File.expand_path('../..', __FILE__)} && bundle exec backup perform -t incremental_backup --triggered_by system"
end

# Remote sync weekly on Sunday at 3:00 AM
every 1.week, at: "3:00 am" do
  command "cd #{File.expand_path('../..', __FILE__)} && bundle exec backup perform -t sync_backup --triggered_by system"
end

# Cleanup old backups monthly
every 1.month, at: "4:00 am" do
  command "cd #{File.expand_path('../..', __FILE__)} && bundle exec backup perform -t full_backup --cleanup"
end
