# encoding: utf-8

# Daily Backup - Generated by rails_nexus
# Skips large/temporary tables for faster backups

Model.new(:daily_backup, '<%= Rails.application.class.module_parent_name %> Daily Backup') do

  ## MySQL [Database]
  database MySQL do |db|
    db.name               = "<%= Rails.configuration.database_configuration[Rails.env]['database'] %>"
    db.port               = <%= Rails.configuration.database_configuration[Rails.env]['port'] || 3306 %>
    db.skip_tables        = []
    db.additional_options = ["--quick"]
  end

  ## Local [Storage]
  store_with Local do |local|
    local.path = 'storage/rails_nexus/backups'
    local.keep = 30
  end

  ## Gzip [Compressor]
  compress_with Gzip
end
